import { test,chromium } from "@playwright/test";

test("To Edit Indivudal Salesforce", async() => {
    test.setTimeout(120000)
const browser = await chromium.launch({channel:"chrome",headless:false})
const browserContext = await browser.newContext()
const page = await browserContext.newPage()
await page.goto("https://login.salesforce.com")
await page.fill("input#username","vineeth1@testleaf.com")
const pwdField= page.locator("input#password")
await pwdField.fill("Testleaf@94")
await page.click("#Login")
await page.waitForLoadState("load")
await page.click("div.slds-icon-waffle")
await page.getByLabel("View All Applications").click()
await page.getByRole('link',{name:'Individuals'}).click()
//await page.getByPlaceholder("Search this list...").fill("Vineeth")
//await page.getByText("Search...").click()
await page.locator("((//a[text()='Tesleaf'])[1]/following::td/span)[5]").click()
await page.locator("div[class *='default visible positioned'] div ul li").nth(0).click()
await page.locator("text='--None--'").nth(0).click()
await page.locator("text='Mr.'").click()
await page.getByPlaceholder("First Name").fill("Vineeth")
await page.getByRole('button', { name: 'Save', exact: true }).click()
//await page.waitForLoadState("load")
await page.waitForTimeout(2000)
let indvidualName= await page.locator("//a[contains(text(),'Tesleaf')]").innerText()
console.log(indvidualName)
await page.waitForTimeout(3000)
})